language: cpp
dist: trusty

sudo: required
bef+ore_install:
  - eval "${MATRIX_EVAL}"

install:
  # - pip install --user -q conan
  - sudo -E pip install conan
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake ../
  - cmake --build .
  - ./bin/test_hello

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
